//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseRush {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CourseRush.Core.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Campus.
        /// </summary>
        internal static string course_campus {
            get {
                return ResourceManager.GetString("course.campus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        internal static string course_class_name {
            get {
                return ResourceManager.GetString("course.class_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Code.
        /// </summary>
        internal static string course_code {
            get {
                return ResourceManager.GetString("course.code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination Method.
        /// </summary>
        internal static string course_examination_method {
            get {
                return ResourceManager.GetString("course.examination_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string course_name {
            get {
                return ResourceManager.GetString("course.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Institution.
        /// </summary>
        internal static string course_offer_institution {
            get {
                return ResourceManager.GetString("course.offer_institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Name.
        /// </summary>
        internal static string course_selection_selection_name {
            get {
                return ResourceManager.GetString("course_selection.selection_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Term.
        /// </summary>
        internal static string course_selection_selection_term {
            get {
                return ResourceManager.GetString("course_selection.selection_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Students/Course Capacity.
        /// </summary>
        internal static string course_student_count {
            get {
                return ResourceManager.GetString("course.student_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        internal static string course_teacher_name {
            get {
                return ResourceManager.GetString("course.teacher_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Method.
        /// </summary>
        internal static string course_teaching_method {
            get {
                return ResourceManager.GetString("course.teaching_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Time Table.
        /// </summary>
        internal static string course_time_table {
            get {
                return ResourceManager.GetString("course.time_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Credits.
        /// </summary>
        internal static string course_total_credit {
            get {
                return ResourceManager.GetString("course.total_credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string course_total_credit_value {
            get {
                return ResourceManager.GetString("course.total_credit.value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Learning Hours.
        /// </summary>
        internal static string course_total_learning_hours {
            get {
                return ResourceManager.GetString("course.total_learning_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hours.
        /// </summary>
        internal static string course_total_learning_hours_value {
            get {
                return ResourceManager.GetString("course.total_learning_hours.value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string course_type {
            get {
                return ResourceManager.GetString("course.type", resourceCulture);
            }
        }
    }
}
