//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseRush.Core {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CourseRush.Core.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Campus.
        /// </summary>
        internal static string course_campus {
            get {
                return ResourceManager.GetString("course.campus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        internal static string course_class_name {
            get {
                return ResourceManager.GetString("course.class_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Code.
        /// </summary>
        internal static string course_code {
            get {
                return ResourceManager.GetString("course.code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elective Course Type.
        /// </summary>
        internal static string course_elective_type {
            get {
                return ResourceManager.GetString("course.elective_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination Method.
        /// </summary>
        internal static string course_examination_method {
            get {
                return ResourceManager.GetString("course.examination_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        internal static string course_group_name {
            get {
                return ResourceManager.GetString("course.group_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string course_name {
            get {
                return ResourceManager.GetString("course.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Institution.
        /// </summary>
        internal static string course_offer_institution {
            get {
                return ResourceManager.GetString("course.offer_institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Method.
        /// </summary>
        internal static string course_selection_method {
            get {
                return ResourceManager.GetString("course.selection_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        internal static string course_selection_method_preset {
            get {
                return ResourceManager.GetString("course.selection_method.preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Select.
        /// </summary>
        internal static string course_selection_method_self_select {
            get {
                return ResourceManager.GetString("course.selection_method.self_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Name.
        /// </summary>
        internal static string course_selection_selection_name {
            get {
                return ResourceManager.GetString("course_selection.selection_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Term.
        /// </summary>
        internal static string course_selection_selection_term {
            get {
                return ResourceManager.GetString("course_selection.selection_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Students/Course Capacity.
        /// </summary>
        internal static string course_student_count {
            get {
                return ResourceManager.GetString("course.student_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        internal static string course_teacher_name {
            get {
                return ResourceManager.GetString("course.teacher_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Method.
        /// </summary>
        internal static string course_teaching_method {
            get {
                return ResourceManager.GetString("course.teaching_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Time Table.
        /// </summary>
        internal static string course_time_table {
            get {
                return ResourceManager.GetString("course.time_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Credits.
        /// </summary>
        internal static string course_total_credit {
            get {
                return ResourceManager.GetString("course.total_credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Score.
        /// </summary>
        internal static string course_total_credit_value {
            get {
                return ResourceManager.GetString("course.total_credit.value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Learning Hours.
        /// </summary>
        internal static string course_total_learning_hours {
            get {
                return ResourceManager.GetString("course.total_learning_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hours.
        /// </summary>
        internal static string course_total_learning_hours_value {
            get {
                return ResourceManager.GetString("course.total_learning_hours.value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string course_type {
            get {
                return ResourceManager.GetString("course.type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task launched.
        /// </summary>
        internal static string task_info_launched {
            get {
                return ResourceManager.GetString("task.info.launched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current task {0} has failed, moving to No.{0} task.
        /// </summary>
        internal static string task_info_prioritized_next {
            get {
                return ResourceManager.GetString("task.info.prioritized_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current task {0} has completed, moving to No.{0} task.
        /// </summary>
        internal static string task_info_sequential_task_next {
            get {
                return ResourceManager.GetString("task.info.sequential_task_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has been cancelled.
        /// </summary>
        internal static string task_log_cancelled {
            get {
                return ResourceManager.GetString("task.log.cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has  completed.
        /// </summary>
        internal static string task_log_complete {
            get {
                return ResourceManager.GetString("task.log.complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has failed.
        /// </summary>
        internal static string task_log_failed {
            get {
                return ResourceManager.GetString("task.log.failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has paused.
        /// </summary>
        internal static string task_log_paused {
            get {
                return ResourceManager.GetString("task.log.paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has resumed.
        /// </summary>
        internal static string task_log_resumed {
            get {
                return ResourceManager.GetString("task.log.resumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task is waiting for retry ({0} time(s)).
        /// </summary>
        internal static string task_log_retry {
            get {
                return ResourceManager.GetString("task.log.retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel selection task: {0} tasks.
        /// </summary>
        internal static string task_parallel_tasks {
            get {
                return ResourceManager.GetString("task.parallel_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritized selection tasks: {0} tasks.
        /// </summary>
        internal static string task_prioritized_tasks {
            get {
                return ResourceManager.GetString("task.prioritized_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selection task: {0}.
        /// </summary>
        internal static string task_remove_task {
            get {
                return ResourceManager.GetString("task.remove_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Retry.
        /// </summary>
        internal static string task_retry_options_always {
            get {
                return ResourceManager.GetString("task.retry_options.always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never Retry.
        /// </summary>
        internal static string task_retry_options_never {
            get {
                return ResourceManager.GetString("task.retry_options.never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Unless Course Full.
        /// </summary>
        internal static string task_retry_options_selection_limit {
            get {
                return ResourceManager.GetString("task.retry_options.selection_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection task.
        /// </summary>
        internal static string task_selection_task {
            get {
                return ResourceManager.GetString("task.selection_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential selection tasks: {0} tasks.
        /// </summary>
        internal static string task_sequential_tasks {
            get {
                return ResourceManager.GetString("task.sequential_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string task_status_cancelled {
            get {
                return ResourceManager.GetString("task.status.cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string task_status_completed {
            get {
                return ResourceManager.GetString("task.status.completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string task_status_failed {
            get {
                return ResourceManager.GetString("task.status.failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to next.
        /// </summary>
        internal static string task_status_next {
            get {
                return ResourceManager.GetString("task.status.next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string task_status_paused {
            get {
                return ResourceManager.GetString("task.status.paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string task_status_running {
            get {
                return ResourceManager.GetString("task.status.running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string task_status_waiting {
            get {
                return ResourceManager.GetString("task.status.waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit selection task: {0}.
        /// </summary>
        internal static string task_submit_task {
            get {
                return ResourceManager.GetString("task.submit_task", resourceCulture);
            }
        }
    }
}
