//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseRush {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CourseRush.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ui_button_apply {
            get {
                return ResourceManager.GetString("ui.button.apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Selected Courses.
        /// </summary>
        public static string ui_button_enqueue_selected_courses {
            get {
                return ResourceManager.GetString("ui.button.enqueue_selected_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ui_button_export {
            get {
                return ResourceManager.GetString("ui.button.export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ui_button_import {
            get {
                return ResourceManager.GetString("ui.button.import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ui_button_login {
            get {
                return ResourceManager.GetString("ui.button.login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ui_button_refresh {
            get {
                return ResourceManager.GetString("ui.button.refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string ui_button_select {
            get {
                return ResourceManager.GetString("ui.button.select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Conflict Course.
        /// </summary>
        public static string ui_button_show_conflict_course {
            get {
                return ResourceManager.GetString("ui.button.show_conflict_course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Full Course.
        /// </summary>
        public static string ui_button_show_full_course {
            get {
                return ResourceManager.GetString("ui.button.show_full_course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Show Courses Of Your Class.
        /// </summary>
        public static string ui_button_show_only_in_class_course {
            get {
                return ResourceManager.GetString("ui.button.show_only_in_class_course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Search Panel.
        /// </summary>
        public static string ui_button_show_search {
            get {
                return ResourceManager.GetString("ui.button.show_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password  cannot be empty.
        /// </summary>
        public static string ui_error_empty_username_password {
            get {
                return ResourceManager.GetString("ui.error.empty_username_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Your University.
        /// </summary>
        public static string ui_label_choose_university {
            get {
                return ResourceManager.GetString("ui.label.choose_university", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string ui_label_index {
            get {
                return ResourceManager.GetString("ui.label.index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ui_label_password {
            get {
                return ResourceManager.GetString("ui.label.password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Selection: {0}#{1}.
        /// </summary>
        public static string ui_label_selection_session {
            get {
                return ResourceManager.GetString("ui.label.selection_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        public static string ui_label_university {
            get {
                return ResourceManager.GetString("ui.label.university", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string ui_label_username {
            get {
                return ResourceManager.GetString("ui.label.username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File....
        /// </summary>
        public static string ui_menu_file_op {
            get {
                return ResourceManager.GetString("ui.menu.file_op", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to select the following coures?.
        /// </summary>
        public static string ui_message_comfirm_select {
            get {
                return ResourceManager.GetString("ui.message.comfirm_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Comfirm.
        /// </summary>
        public static string ui_message_comfirm_select_title {
            get {
                return ResourceManager.GetString("ui.message.comfirm_select_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time conflict occurs when selecting {0}:.
        /// </summary>
        public static string ui_message_course_conflict {
            get {
                return ResourceManager.GetString("ui.message.course_conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict with {0} on {1}.
        /// </summary>
        public static string ui_message_course_conflict_info {
            get {
                return ResourceManager.GetString("ui.message.course_conflict.info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} coures  to selection queue.
        /// </summary>
        public static string ui_message_course_selected {
            get {
                return ResourceManager.GetString("ui.message.course_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University Of Debugging Professional.
        /// </summary>
        public static string university_Debug {
            get {
                return ResourceManager.GetString("university.Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunan University.
        /// </summary>
        public static string university_HNU {
            get {
                return ResourceManager.GetString("university.HNU", resourceCulture);
            }
        }
    }
}
